version: "3.8"

services:
  # MySQL
  database:
    container_name: flutter-database
    image: mysql:8
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=flutter
    ports:
      - 3306:3306
    volumes:
      - flutter-volume:/var/lib/mysql
    networks:
      - flutter-network

networks:
  flutter-network:
    driver: bridge

volumes:
  flutter-volume:
